insert into communities (name, admin_user_id) values ('Schoen-Kutch', 51);
insert into communities (name, admin_user_id) values ('Reichert LLC', 97);
insert into communities (name, admin_user_id) values ('Tillman-Quigley', 34);
insert into communities (name, admin_user_id) values ('Hahn Inc', 51);
insert into communities (name, admin_user_id) values ('Hintz-Raynor', 45);
insert into communities (name, admin_user_id) values ('Beatty-Mayert', 63);
insert into communities (name, admin_user_id) values ('Barrows Group', 58);
insert into communities (name, admin_user_id) values ('Hoppe-Fay', 75);
insert into communities (name, admin_user_id) values ('Rice-Stokes', 40);
insert into communities (name, admin_user_id) values ('Hoppe Group', 44);
insert into communities (name, admin_user_id) values ('Franecki and Sons', 93);
insert into communities (name, admin_user_id) values ('Christiansen, Grant and Larkin', 26);
insert into communities (name, admin_user_id) values ('Brekke Group', 77);
insert into communities (name, admin_user_id) values ('Swift-Ritchie', 7);
insert into communities (name, admin_user_id) values ('Metz, Schmidt and Durgan', 20);
insert into communities (name, admin_user_id) values ('Larson-Wisoky', 63);
insert into communities (name, admin_user_id) values ('Renner Inc', 26);
insert into communities (name, admin_user_id) values ('O''Keefe, Stanton and Osinski', 43);
insert into communities (name, admin_user_id) values ('Paucek-VonRueden', 76);
insert into communities (name, admin_user_id) values ('Macejkovic, Runolfsson and Russel', 15);
insert into communities (name, admin_user_id) values ('Kiehn Group', 15);
insert into communities (name, admin_user_id) values ('Rolfson-Gaylord', 30);
insert into communities (name, admin_user_id) values ('Auer, Parker and Durgan', 37);
insert into communities (name, admin_user_id) values ('Windler Inc', 58);
insert into communities (name, admin_user_id) values ('Leuschke-Abshire', 46);
insert into communities (name, admin_user_id) values ('Yundt and Sons', 43);
insert into communities (name, admin_user_id) values ('Hilll and Sons', 92);
insert into communities (name, admin_user_id) values ('Krajcik and Sons', 48);
insert into communities (name, admin_user_id) values ('Gibson-Beer', 62);
insert into communities (name, admin_user_id) values ('Beatty, Greenfelder and Lynch', 77);
insert into communities (name, admin_user_id) values ('Spinka-McCullough', 98);
insert into communities (name, admin_user_id) values ('Hintz LLC', 31);
insert into communities (name, admin_user_id) values ('McClure LLC', 80);
insert into communities (name, admin_user_id) values ('Howe Group', 95);
insert into communities (name, admin_user_id) values ('Waelchi-Robel', 85);
insert into communities (name, admin_user_id) values ('Sipes, Thompson and Rippin', 50);
insert into communities (name, admin_user_id) values ('Buckridge, Dibbert and Jast', 22);
insert into communities (name, admin_user_id) values ('Stark LLC', 48);
insert into communities (name, admin_user_id) values ('Schimmel, Muller and Aufderhar', 91);
insert into communities (name, admin_user_id) values ('Torp, Nicolas and Lemke', 47);
insert into communities (name, admin_user_id) values ('Swift and Sons', 9);
insert into communities (name, admin_user_id) values ('Kuphal-Willms', 19);
insert into communities (name, admin_user_id) values ('Cummings-Sporer', 72);
insert into communities (name, admin_user_id) values ('Abernathy, Hilll and Connelly', 7);
insert into communities (name, admin_user_id) values ('Bayer LLC', 95);
insert into communities (name, admin_user_id) values ('Reichel, Durgan and Hammes', 62);
insert into communities (name, admin_user_id) values ('Lebsack Group', 99);
insert into communities (name, admin_user_id) values ('Raynor, Lind and Mueller', 24);
insert into communities (name, admin_user_id) values ('Feeney-Mante', 69);
insert into communities (name, admin_user_id) values ('Sawayn-Nolan', 44);
insert into communities (name, admin_user_id) values ('Marks, Yost and Von', 73);
insert into communities (name, admin_user_id) values ('Rice Group', 51);
insert into communities (name, admin_user_id) values ('Pacocha, Howe and Renner', 44);
insert into communities (name, admin_user_id) values ('Ward, McGlynn and Rogahn', 93);
insert into communities (name, admin_user_id) values ('Steuber-Powlowski', 66);
insert into communities (name, admin_user_id) values ('Zemlak, Dickinson and Waters', 50);
insert into communities (name, admin_user_id) values ('Davis-Lehner', 46);
insert into communities (name, admin_user_id) values ('Bailey Group', 37);
insert into communities (name, admin_user_id) values ('Stanton-Beahan', 18);
insert into communities (name, admin_user_id) values ('Daniel-Schmeler', 88);
insert into communities (name, admin_user_id) values ('Dicki Inc', 96);
insert into communities (name, admin_user_id) values ('Kuhn, Miller and Herzog', 94);
insert into communities (name, admin_user_id) values ('O''Kon, Yost and Okuneva', 93);
insert into communities (name, admin_user_id) values ('Gibson-Kris', 8);
insert into communities (name, admin_user_id) values ('Jones Group', 58);
insert into communities (name, admin_user_id) values ('Green, Swift and Haley', 14);
insert into communities (name, admin_user_id) values ('Quitzon Inc', 12);
insert into communities (name, admin_user_id) values ('Reilly, Swift and Grimes', 9);
insert into communities (name, admin_user_id) values ('Connelly LLC', 81);
insert into communities (name, admin_user_id) values ('Jaskolski-Hettinger', 18);
insert into communities (name, admin_user_id) values ('Robel, Cartwright and Towne', 87);
insert into communities (name, admin_user_id) values ('Wehner, Conn and Beahan', 90);
insert into communities (name, admin_user_id) values ('Friesen-Welch', 57);
insert into communities (name, admin_user_id) values ('Bednar, Blanda and Lowe', 77);
insert into communities (name, admin_user_id) values ('Harber-Zemlak', 6);
insert into communities (name, admin_user_id) values ('Herman-Thiel', 57);
insert into communities (name, admin_user_id) values ('Beier LLC', 25);
insert into communities (name, admin_user_id) values ('Armstrong-Bins', 96);
insert into communities (name, admin_user_id) values ('Feest-Dooley', 72);
insert into communities (name, admin_user_id) values ('Kihn, Hartmann and Bode', 75);
insert into communities (name, admin_user_id) values ('Nienow-Lindgren', 89);
insert into communities (name, admin_user_id) values ('Jakubowski-Little', 83);
insert into communities (name, admin_user_id) values ('Koch-Grady', 68);
insert into communities (name, admin_user_id) values ('Huels-Willms', 46);
insert into communities (name, admin_user_id) values ('Yundt LLC', 72);
insert into communities (name, admin_user_id) values ('Vandervort Group', 70);
insert into communities (name, admin_user_id) values ('Grimes, Luettgen and Wisoky', 26);
insert into communities (name, admin_user_id) values ('Kertzmann, Maggio and Schuppe', 32);
insert into communities (name, admin_user_id) values ('Johns and Sons', 48);
insert into communities (name, admin_user_id) values ('Anderson-Cartwright', 14);
insert into communities (name, admin_user_id) values ('Auer, Rutherford and Feeney', 77);
insert into communities (name, admin_user_id) values ('Goldner-Howell', 71);
insert into communities (name, admin_user_id) values ('Kshlerin, Bahringer and Schultz', 34);
insert into communities (name, admin_user_id) values ('Glover, Vandervort and Kirlin', 90);
insert into communities (name, admin_user_id) values ('Ziemann, Sporer and Howe', 35);
insert into communities (name, admin_user_id) values ('Gaylord, Dickens and O''Kon', 64);
insert into communities (name, admin_user_id) values ('Rohan Group', 33);
insert into communities (name, admin_user_id) values ('Mosciski Inc', 57);
insert into communities (name, admin_user_id) values ('Ankunding-Tromp', 55);
insert into communities (name, admin_user_id) values ('Hane LLC', 57);
