DROP FUNCTION IF EXISTS FIBONACCI;

DELIMITER //
CREATE FUNCTION FIBONACCI(n INT)
RETURNS INT DETERMINISTIC 
BEGIN
	DECLARE i INT DEFAULT 0;
	DECLARE x1 INT DEFAULT 0;
	DECLARE x2 INT DEFAULT 0;
	DECLARE x INT DEFAULT 0;
	loop1: WHILE i <= n DO
		IF i = 0 THEN 
			SET i = i + 1;
			ITERATE loop1;
		ELSEIF i = 1 THEN 
			SET x = 1;
		ELSE 
			SET x2 = x1;
			SET x1 = x;
			SET x = x1 + x2;
		END IF;
		SET i = i + 1;
	END WHILE loop1;
	RETURN x;
END //
DELIMITER ;

SELECT FIBONACCI(10);




